title: Chloe Liu # your name (or website title) here
logo: "/images/photo3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  4 years of Data Product Manager, expertise in big data governance, architecting, visualization and application, as well as product design, driving data-driven insights and strategies. 
  <br><br>
  Location: Guangzhou, China
  <br><br>
  E-mail: liuxinchi9@gmail.com
  
theme: jekyll-theme-minimal
