title: Chloe Liu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of Data Product Manager experience with e-commerce experience. Familiar with big data and clickstream data related domain. 
  <br><br>
  Currently in the SHEIN Artificial Intelligence Digital Center as Data Product Manager. Mainly working for implementing clickstream data governance and behavior analysis platform. 
  <br><br>
  
theme: jekyll-theme-minimal
